version: "3"

services:
    server:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        volumes:
            - /app/node_modules
            - /DDL
            - .:/app
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - dbprova:/app/mysql
            - ./DDL:/docker-entrypoint-initdb.d
volumes:
    dbprova: