FROM node:14

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install validator
RUN npm install body-parser
RUN npm install cors
RUN npm install mysql
RUN npm install redis
RUN npm install uuid
RUN npm install aes256

COPY ./ ./

CMD [ "npm", "start" ]